version: '2.4'
services:
  neo4j-workshop:
    image: neo4j:5-community
    container_name: neo4j-workshop
    hostname: neo4j-workshop
    mem_limit: 4G
    restart: unless-stopped
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - ./neo4j_data_volume:/data
      - ./neo4j_logs_volume:/logs
      - ./neo4j_import_volume:/import
      - ./neo4j_plugins_volume:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_dbms.security.procedures.allowlist=apoc.*,gds.*
      - NEO4J_apoc.import.file.enabled=true
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;"]
      interval: 10s
      timeout: 5s
      retries: 10
